use MSSQL

--Câu 21: Thống kê có bao nhiêu giáo viên có học vị là “CN”, “KS”, “Ths”, “TS”, “PTS” trong mỗi khoa.
SELECT HOCVI,COUNT(*)AS SOLUONG
FROM GIAOVIEN
GROUP BY HOCVI;
--Câu 22: Mỗi môn học thống kê số lượng học viên theo kết quả (đạt và không đạt).
SELECT KQUA, COUNT(MAHV) AS SOLUONG
FROM KETQUATHI
GROUP BY KQUA;
--Câu 23: Cho biết giáo viên (mã giáo viên, họ tên) là giáo viên chủ nhiệm của một lớp, đồng thời dạy cho lớp đó ít nhất một môn học.
SELECT GIAOVIEN.MAGV,GIAOVIEN.HOTEN, COUNT(GIANGDAY.MAMH) AS SOMONDAY
FROM GIAOVIEN,LOP,GIANGDAY
WHERE GIAOVIEN.MAGV = GIANGDAY.MAGV AND GIAOVIEN.MAGV=LOP.MAGVCN AND LOP.MALOP=GIANGDAY.MALOP
GROUP BY GIAOVIEN.MAGV,GIAOVIEN.HOTEN;
--24.Cho biết họ tên lớp trưởng của lớp có sỉ số cao nhất.
SELECT hv.HO,hv.TEN FROM HOCVIEN hv WHERE hv.MAHV IN (SELECT l.TRGLOP FROM LOP l WHERE l.SISO= (SELECT MAX(SISO) FROM LOP));
--25.Cho biết họ tên những LOPTRG thi không đạt quá 3 môn (mỗi môn đều thi không đạt ở tất cả các lần thi).
SELECT hv.HO,hv.TEN FROM HOCVIEN hv JOIN LOP lop ON hv.MAHV=lop.TRGLOP JOIN (SELECT kqt.MAHV,kqt.MAMH,kqt.KQUA FROM KETQUATHI kqt
WHERE kqt.KQUA='Khong Dat' GROUP BY kqt.MAHV,kqt.MAMH,kqt.KQUA HAVING COUNT(kqt.MAMH)=COUNT(kqt.KQUA)) a ON a.MAHV =hv.MAHV
GROUP BY hv.HO, hv.TEN HAVING COUNT(*)>3;
--26.Cho biết học viên (mã học viên, họ tên) có số môn đạt điểm 9,10 nhiều nhất.
SELECT hv.MAHV , hv.HO, hv.TEN FROM HOCVIEN hv JOIN KETQUATHI kqt ON hv.MAHV =kqt.MAHV WHERE  kqt.DIEM >=9.00
GROUP BY hv.MAHV,hv.HO,hv.TEN HAVING COUNT(kqt.DIEM)>=ALL(SELECT COUNT(DIEM) FROM KETQUATHI WHERE DIEM>=9.00 GROUP BY MAHV);
--27. Trong từng lớp, Cho biết học viên (mã học viên, họ tên) có số môn đạt điểm 9,10 nhiều nhất. 
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN
FROM HOCVIEN JOIN KETQUATHI 
ON HOCVIEN.MAHV = KETQUATHI.MAHV 
WHERE KETQUATHI.DIEM >= 9.00
GROUP BY HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN
HAVING count(KETQUATHI.DIEM) >=ALL(SELECT COUNT(DIEM) 
									FROM KETQUATHI
									WHERE KETQUATHI.DIEM >= 9.00
									GROUP BY KETQUATHI.MAHV);
	
--28.Trong từng học kỳ của từng năm, mỗi giáo viên phân công dạy bao nhiêu môn học, bao nhiêu lớp.
SELECT GIANGDAY.HOCKY, GIANGDAY.NAM,GIAOVIEN.MAGV, GIAOVIEN.HOTEN, COUNT(GIANGDAY.MAMH) AS 'SOMONHOC', COUNT(GIANGDAY.MALOP) AS 'SOLOPGIANGDAY'
FROM GIAOVIEN INNER JOIN GIANGDAY 
ON GIAOVIEN.MAGV = GIANGDAY.MAGV
GROUP BY GIANGDAY.HOCKY, GIANGDAY.NAM,GIAOVIEN.MAGV, GIAOVIEN.HOTEN;

--29.  Trong từng học kỳ của từng năm, Cho biết giáo viên (mã giáo viên, họ tên) giảng dạy nhiều nhất.
SELECT GIANGDAY.HOCKY, GIANGDAY.NAM, GIAOVIEN.MAGV, GIAOVIEN.HOTEN,COUNT(GIANGDAY.MALOP)AS 'SOLOPGIANGDAY'
FROM GIANGDAY INNER JOIN GIAOVIEN
ON GIANGDAY.MAGV = GIAOVIEN.MAGV
GROUP BY GIANGDAY.HOCKY, GIANGDAY.NAM,GIAOVIEN.MAGV, GIAOVIEN.HOTEN
HAVING COUNT(GIANGDAY.MALOP) >=ALL(SELECT COUNT(GIANGDAY.MALOP) AS 'SOLOPGIANGDAY'
									FROM GIANGDAY INNER JOIN GIAOVIEN
									ON GIANGDAY.MAGV = GIAOVIEN.MAGV);
--30. Cho biết môn học (mã môn học, tên môn học) có nhiều học viên thi không đạt (ở lần thi thứ 1) nhất. 
SELECT KQ.MAMH, TENMH
FROM MONHOC MH INNER JOIN KETQUATHI KQ ON KQ.MAMH = MH.MAMH
WHERE KQUA = 'Khong Dat' AND LT=1
GROUP BY KQ.MAMH, TENMH
HAVING COUNT(MAHV) = (
	SELECT TOP 1 COUNT(*)
	FROM KETQUATHI
	WHERE KQUA = 'Khong Dat' AND LT=1
	GROUP BY MAMH
	ORDER BY COUNT(*) DESC);
